openapi: 3.0.3
info:
  title: Play Integrity Verification API
  description: |-
    Stateless endpoint for decrypting and verifying Play Integrity tokens.

    This endpoint acts as a thin proxy between the mobile client (who obtains
    an encrypted token from Google's Play Integrity API) and Google's
    verification service. The endpoint decrypts the token and returns the
    verdict fields.

    **IMPORTANT**: This endpoint does NOT enforce integrity verdicts or store
    user state. Enforcement is entirely client-side. The backend is stateless
    and only decrypts the encrypted token.
  version: 1.0.0
  contact:
    name: Exam App Team
    url: https://github.com/danilocasim/exam-app
servers:
  - url: http://localhost:3000
    description: Local development
  - url: https://api.examapp.com
    description: Production

paths:
  /api/integrity/verify:
    post:
      summary: Decrypt and verify Play Integrity token
      description: |-
        Accepts an encrypted Play Integrity token from the mobile client,
        decrypts it using Google's Play Integrity verification API, and
        returns the decrypted verdict.

        **Important**: 
        - Token must be obtained from Google Play Integrity API on client
        - Decryption requires service account credentials (backend-only)
        - Verdict is returned as-is; client enforces blocking logic
        - Endpoint is stateless; verdict NOT stored in database
        - No authentication required (token is encrypted; only possessor of
          app signing key can decrypt)
      tags:
        - Integrity
      operationId: verifyIntegrityToken
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VerifyTokenRequest'
            examples:
              valid_token:
                summary: Valid encrypted token from Google Play Integrity API
                value:
                  token: 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9...'
      responses:
        '200':
          description: |-
            Token successfully decrypted and verdict returned.
            All verdict fields included; client interprets results.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IntegrityVerifyResponse'
              examples:
                success:
                  summary: All verdicts PASS
                  value:
                    success: true
                    verdict:
                      appRecognitionVerdict: PLAY_RECOGNIZED
                      appLicensingVerdict: LICENSED
                      deviceRecognitionVerdict: MEETS_DEVICE_INTEGRITY
                partially_evaluated:
                  summary: Some verdicts UNEVALUATED (transient)
                  value:
                    success: true
                    verdict:
                      appRecognitionVerdict: PLAY_RECOGNIZED
                      appLicensingVerdict: UNKNOWN
                      deviceRecognitionVerdict: MEETS_DEVICE_INTEGRITY
        '400':
          description: |-
            Bad request or invalid token format.
            Client should treat as transient error and retry.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                invalid_token:
                  summary: Token format invalid
                  value:
                    success: false
                    error: 'Invalid token format. Token must be a valid JWT.'
        '500':
          description: |-
            Server error (Google API unavailable, decryption failure, etc).
            Client should treat as transient and retry with backoff.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                google_api_down:
                  summary: Google Play Integrity API temporarily unavailable
                  value:
                    success: false
                    error: 'Google Play Integrity API unavailable. Please try again later.'
        '503':
          description: |-
            Service unavailable (backend maintenance or overload).
            Client should retry.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                service_unavailable:
                  summary: Backend temporarily unavailable
                  value:
                    success: false
                    error: 'Service temporarily unavailable. Please try again.'

components:
  schemas:
    VerifyTokenRequest:
      type: object
      required:
        - token
      properties:
        token:
          type: string
          description: |-
            Encrypted Play Integrity token obtained from Google Play Integrity API.
            Must be a valid JWT signed by Google using the app's signing key.
          format: jwt
          example: 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9...'

    IntegrityVerifyResponse:
      type: object
      required:
        - success
      properties:
        success:
          type: boolean
          description: Always true if response is 200 (verdict decoded successfully)
          example: true
        verdict:
          $ref: '#/components/schemas/PlayIntegrityVerdict'
          description: |-
            Decrypted Play Integrity verdict. Returned on successful decryption.
            Client interprets these fields to decide pass/fail.
        error:
          type: string
          description: Error message (only populated on failure status codes)
          example: null

    PlayIntegrityVerdict:
      type: object
      required:
        - appRecognitionVerdict
        - appLicensingVerdict
        - deviceRecognitionVerdict
      properties:
        appRecognitionVerdict:
          type: string
          enum:
            - PLAY_RECOGNIZED
            - UNRECOGNIZED_VERSION
            - UNKNOWN
          description: |-
            Whether the app is recognized by Google Play.

            - `PLAY_RECOGNIZED`: App installed from Play Store, signature matches release key
            - `UNRECOGNIZED_VERSION`: App signature does NOT match Play Store signing key (sideload or re-signed)
            - `UNKNOWN`: Google could not evaluate (transient, should retry)
          example: PLAY_RECOGNIZED
        appLicensingVerdict:
          type: string
          enum:
            - LICENSED
            - UNLICENSED
            - UNKNOWN
          description: |-
            Whether the user is licensed to use the app (purchased or Install from Play Store).

            - `LICENSED`: User purchased or installed the app from Play Store
            - `UNLICENSED`: User did not purchase/install from Play Store (sideload on non-Play device)
            - `UNKNOWN`: Google could not evaluate (transient, should retry)
          example: LICENSED
        deviceRecognitionVerdict:
          type: string
          enum:
            - MEETS_DEVICE_INTEGRITY
            - MEETS_STRONG_INTEGRITY
            - UNKNOWN
          description: |-
            Whether the device meets Google's integrity requirements.

            - `MEETS_DEVICE_INTEGRITY`: Device integrity check passes (basic, sufficient for our use case)
            - `MEETS_STRONG_INTEGRITY`: Device passes stricter checks (optional; we don't require)
            - `UNKNOWN`: Google could not evaluate (transient, should retry)
          example: MEETS_DEVICE_INTEGRITY
        tokenPayloadExternal:
          type: object
          description: |-
            Additional fields from the Play Integrity token (optional, for debugging).
            Not required for verification decision.
          additionalProperties: true
          example:
            timestampMillis: 1676405000000
            nonce: 'abc123...'

    ErrorResponse:
      type: object
      required:
        - success
        - error
      properties:
        success:
          type: boolean
          description: Always false for error responses
          example: false
        error:
          type: string
          description: Human-readable error message
          example: 'Google Play Integrity API request failed'

  responses:
    UnauthorizedError:
      description: Authentication required (not applicable for this endpoint; token is encrypted)
    NotFoundError:
      description: Endpoint not found
    InternalServerError:
      description: Server error; client should retry

tags:
  - name: Integrity
    description: |-
      Play Integrity verification endpoints.

      **Architecture**: These endpoints are stateless proxies. The backend
      decrypts tokens obtained by the mobile client from Google's Play
      Integrity API. Enforcement of verdicts (blocking vs. allowing access)
      is performed entirely by the mobile client.

x-security-note: |-
  **No Additional Authentication Required**

  Play Integrity tokens are encrypted using the app's signing key (stored
  securely by Google). Only the mobile app (with the matching signing key
  in Google Play Console) can obtain a valid token. Therefore, this endpoint
  does not require additional API key or bearer token authentication.

  The token itself serves as proof of origin (app signature verified by Google).
