/**
 * T164: Integrity Service
 *
 * Service for verifying Google Play Integrity tokens.
 * This is a stateless service that acts as a proxy to Google's Play Integrity API.
 *
 * Flow:
 * 1. Mobile client requests Play Integrity token from Google API
 * 2. Mobile client sends encrypted token to this backend endpoint
 * 3. Backend decrypts token using Google Play Console service account credentials
 * 4. Backend returns verdict to mobile client
 * 5. Mobile client enforces block/allow decision based on verdict
 *
 * Important: This service does NOT store verdicts or user data. It is completely stateless.
 */
import {
  Injectable,
  BadRequestException,
  InternalServerErrorException,
  Logger,
} from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { google } from 'googleapis';
import { GoogleAuth } from 'google-auth-library';
import { PlayIntegrityVerdict } from './dto/integrity-verdict.dto';
import * as fs from 'fs';
import * as path from 'path';

@Injectable()
export class IntegrityService {
  private readonly logger = new Logger(IntegrityService.name);
  private readonly projectNumber: string;
  private readonly serviceAccountKeyPath: string;
  private googleAuth: GoogleAuth | null = null;

  constructor(private readonly configService: ConfigService) {
    this.projectNumber =
      this.configService.get<string>(
        'playIntegrity.googleCloudProjectNumber',
      ) || '';
    this.serviceAccountKeyPath =
      this.configService.get<string>(
        'playIntegrity.googleServiceAccountKeyPath',
      ) || '';

    if (!this.projectNumber) {
      this.logger.warn(
        'GOOGLE_CLOUD_PROJECT_NUMBER not configured. Play Integrity verification will fail.',
      );
    }

    if (!this.serviceAccountKeyPath) {
      this.logger.warn(
        'GOOGLE_SERVICE_ACCOUNT_KEY_PATH not configured. Play Integrity verification will fail.',
      );
    }
  }

  /**
   * Initialize Google Auth client with service account credentials
   */
  private async getGoogleAuth(): Promise<GoogleAuth> {
    if (this.googleAuth) {
      return this.googleAuth;
    }

    try {
      // Try inline JSON env var first, then fall back to file path
      const inlineKey = this.configService.get<string>(
        'playIntegrity.googleServiceAccountKey',
      );
      let credentials: Record<string, unknown>;

      if (inlineKey) {
        this.logger.log(
          'Using inline GOOGLE_SERVICE_ACCOUNT_KEY environment variable',
        );
        credentials = JSON.parse(inlineKey);
      } else {
        // Resolve service account key path
        const keyPath = path.resolve(process.cwd(), this.serviceAccountKeyPath);

        // Check if file exists
        if (!fs.existsSync(keyPath)) {
          throw new Error(
            `Service account key file not found at: ${keyPath}. Set GOOGLE_SERVICE_ACCOUNT_KEY env var or provide the file.`,
          );
        }

        // Read and parse service account credentials
        const keyFileContent = fs.readFileSync(keyPath, 'utf8');
        credentials = JSON.parse(keyFileContent);
      }

      // Create Google Auth client
      this.googleAuth = new GoogleAuth({
        credentials,
        scopes: ['https://www.googleapis.com/auth/playintegrity'],
      });

      this.logger.log('Google Auth client initialized successfully');
      return this.googleAuth;
    } catch (error) {
      this.logger.error(
        `Failed to initialize Google Auth: ${error instanceof Error ? error.message : 'Unknown error'}`,
      );
      throw new InternalServerErrorException(
        'Failed to initialize Google authentication',
      );
    }
  }

  /**
   * Verify Play Integrity token by decrypting it with Google's API
   *
   * @param token - Encrypted token from Google Play Integrity API (generated by mobile client)
   * @returns Promise<PlayIntegrityVerdict> - Decrypted verdict with app/licensing/device recognition results
   * @throws BadRequestException - Invalid token format or token verification failed
   * @throws InternalServerErrorException - Google API unavailable or timeout
   */
  async verifyToken(token: string): Promise<PlayIntegrityVerdict> {
    this.logger.debug(
      `Verifying Play Integrity token (length: ${token?.length || 0})`,
    );

    // Validate inputs
    if (!token || token.trim().length === 0) {
      throw new BadRequestException('Token is required');
    }

    if (!this.projectNumber) {
      throw new InternalServerErrorException(
        'Play Integrity verification not configured: missing project number',
      );
    }

    try {
      // Get authenticated client
      const auth = await this.getGoogleAuth();
      const authClient = await auth.getClient();

      // Create Play Integrity API client
      const playintegrity = google.playintegrity({
        version: 'v1',
        auth: authClient as any,
      });

      // Decode token using Google Play Integrity API
      const packageName = 'com.awsccp.examprep'; // From app.json
      const response = await playintegrity.v1.decodeIntegrityToken({
        packageName,
        requestBody: {
          integrityToken: token,
        },
      });

      this.logger.debug('Play Integrity API response received');

      // Extract token payload info
      const tokenPayloadExternal = response.data.tokenPayloadExternal;

      if (!tokenPayloadExternal) {
        throw new BadRequestException('Invalid token: missing payload');
      }

      // Extract verdicts from response
      const appIntegrity = tokenPayloadExternal.appIntegrity;
      const accountDetails = tokenPayloadExternal.accountDetails;
      const deviceIntegrity = tokenPayloadExternal.deviceIntegrity;

      // Map verdicts to our interface with type safety
      const appRecognitionVerdict = appIntegrity?.appRecognitionVerdict as
        | 'PLAY_RECOGNIZED'
        | 'UNRECOGNIZED_VERSION'
        | 'UNKNOWN';
      const appLicensingVerdict = accountDetails?.appLicensingVerdict as
        | 'LICENSED'
        | 'UNLICENSED'
        | 'UNKNOWN';
      const deviceRecognitionVerdict = Array.isArray(
        deviceIntegrity?.deviceRecognitionVerdict,
      )
        ? deviceIntegrity.deviceRecognitionVerdict.includes(
            'MEETS_STRONG_INTEGRITY',
          )
          ? 'MEETS_STRONG_INTEGRITY'
          : deviceIntegrity.deviceRecognitionVerdict.includes(
                'MEETS_DEVICE_INTEGRITY',
              )
            ? 'MEETS_DEVICE_INTEGRITY'
            : 'UNKNOWN'
        : ('UNKNOWN' as const);

      const verdict: PlayIntegrityVerdict = {
        appRecognitionVerdict: appRecognitionVerdict || 'UNKNOWN',
        appLicensingVerdict: appLicensingVerdict || 'UNKNOWN',
        deviceRecognitionVerdict: deviceRecognitionVerdict || 'UNKNOWN',
      };

      this.logger.log(
        `Verification complete: app=${verdict.appRecognitionVerdict}, license=${verdict.appLicensingVerdict}, device=${verdict.deviceRecognitionVerdict}`,
      );

      if (
        verdict.appRecognitionVerdict === 'UNRECOGNIZED_VERSION' ||
        verdict.appLicensingVerdict === 'UNLICENSED' ||
        verdict.deviceRecognitionVerdict === 'UNKNOWN'
      ) {
        this.logger.warn(
          `Integrity check failed: app=${verdict.appRecognitionVerdict}, license=${verdict.appLicensingVerdict}, device=${verdict.deviceRecognitionVerdict}`,
        );
      }

      return verdict;
    } catch (error) {
      // Handle specific error types
      if (error instanceof BadRequestException) {
        throw error;
      }

      if (error instanceof InternalServerErrorException) {
        throw error;
      }

      // Log error details
      this.logger.error(
        `Token verification failed: ${error instanceof Error ? error.message : 'Unknown error'}`,
      );

      // Check if it's a Google API error
      if (typeof error === 'object' && error !== null && 'response' in error) {
        const apiError = error as any;
        const status = apiError.response?.status;
        const message = apiError.response?.data?.error?.message;

        if (status === 400) {
          throw new BadRequestException(
            message || 'Invalid token or token expired',
          );
        }

        if (status === 401 || status === 403) {
          throw new InternalServerErrorException(
            'Play Integrity API authentication failed',
          );
        }

        if (status >= 500) {
          throw new InternalServerErrorException(
            'Google Play Integrity API temporarily unavailable',
          );
        }
      }

      // Generic error
      throw new InternalServerErrorException(
        'Token verification failed due to unexpected error',
      );
    }
  }
}
