/**
 * T158: Verify Token Request DTO
 * 
 * Request body for POST /api/integrity/verify endpoint.
 * Contains the encrypted Play Integrity token from the mobile client.
 */
import { IsNotEmpty, IsString } from 'class-validator';

/**
 * Request DTO for Play Integrity token verification
 */
export class VerifyTokenRequest {
  /**
   * Encrypted token from Google Play Integrity API
   * Generated by mobile client using @react-native-google-signin/google-signin
   * Must be decrypted server-side using Google Play Console credentials
   */
  @IsString()
  @IsNotEmpty()
  token: string;
}
